name: Go

on:
  push:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build_linux
      run: go build -v -o main .
      
    - name: zip_linux
      run:  zip -r main.zip main
      
    - name: Build_mac
      run: CGO_ENABLED=0 GOOS=darwin  GOARCH=arm64 go build -v -o main_arm64 .
      
    - name: zip_mac
      run:  zip -r main_arm64.zip main_arm64
      
    - uses: actions/upload-artifact@v1
      with:
        name: main
        path: main.zip
      name: 'Upload Package'

    - uses: actions/upload-artifact@v1
      with:
        name: main_arm64
        path: main_arm64.zip
      name: 'Upload Package'
