name: Go

on:
  push:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go build -v -o main .
      
    - name: zip
      run:  zip -r main.zip main
      
      
    - uses: actions/upload-artifact@v1
      with:
        name: main
        path: main.zip
      name: 'Upload Package'
